// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsjDgsFZj0ucihjMsf-bJA0RI2UGqEKaM',
    appId: '1:190946429583:web:d59f738de42a50ee9b7efa',
    messagingSenderId: '190946429583',
    projectId: 'emotional-social',
    authDomain: 'emotional-social.firebaseapp.com',
    storageBucket: 'emotional-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnOir2Hjzy8OddphESp3vnOlIWhP7rSuA',
    appId: '1:190946429583:android:27deed3666c66b9b9b7efa',
    messagingSenderId: '190946429583',
    projectId: 'emotional-social',
    storageBucket: 'emotional-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChAPyRBhUkz8WxOvWDCJn8dNcXpwcE8Y0',
    appId: '1:190946429583:ios:369b30aea9708d1b9b7efa',
    messagingSenderId: '190946429583',
    projectId: 'emotional-social',
    storageBucket: 'emotional-social.appspot.com',
    iosBundleId: 'com.avci.emotionalSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChAPyRBhUkz8WxOvWDCJn8dNcXpwcE8Y0',
    appId: '1:190946429583:ios:369b30aea9708d1b9b7efa',
    messagingSenderId: '190946429583',
    projectId: 'emotional-social',
    storageBucket: 'emotional-social.appspot.com',
    iosBundleId: 'com.avci.emotionalSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsjDgsFZj0ucihjMsf-bJA0RI2UGqEKaM',
    appId: '1:190946429583:web:2580def224185bb39b7efa',
    messagingSenderId: '190946429583',
    projectId: 'emotional-social',
    authDomain: 'emotional-social.firebaseapp.com',
    storageBucket: 'emotional-social.appspot.com',
  );

}